name: web_client

services:
  webclient_tachonogy:
    image: ${DOCKER_REGISTRY-}webclienttachonogy
    build:
      context: PRN232_WebClient_Tachonogy
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - ASPNETCORE_URLS=http://+:9000
      - ASPNETCORE_ENVIRONMENT=Docker
      - ApiGateway__BaseUrl=http://gateway:8080
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
    external: true